### PR TITLE
added CSS to apply scrollbar when messages overflow

### PR DESCRIPTION
**Pull request by hungthezorba**
I have added CSS to fix the scrollbar issue on message box. Please check if the solution fix your problem.

### CODE REVIEW

**Comment by olavfosse** [comment]
Very nice. This fix works for me across Chrome/Safari/Firefox. Thanks a lot!

Some small suggestions for your next PR:
- Start with a uppercase imperative verb ("Add" as opposed to "added")
- Append "Fix #x" to automatically close Issue X on merge. For example the commit message "Add scrollbar to messages. Fix #6" would automatically close #6 on merge. Fix can be exchanged with close/closes/closed/fixes/fixed/resolve/resolves/resolved and have the same effect. 
- It is best to remove trailing whitespace as git does not like that and it looks ugly in the diffs, see below.

```
$ curl https://github.com/olav35/liracer-rewrite/commit/f75fc0d025a30a27f3a6ce791b45925fbba855fc.patch | git am
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   945  100   945    0     0   2460      0 --:--:-- --:--:-- --:--:--  2454
Applying: added CSS to apply scrollbar when messages overflow
.git/rebase-apply/patch:14: trailing whitespace.
  flex: 1 1 auto; 
warning: 1 line adds whitespace errors.
$ g s
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
````
image

**Comment by olavfosse** [comment]
I patched my master, and added the hacktoberfest-accepted label. Closing.

**Comment by hungthezorba** [comment]
Thank you for your suggestion, I do not have much experience in contributing to open source. So, I really appreciate for your instruction.

Cheers

**Comment by olavfosse** [comment]
No problem. Thanks for the PR.

**Pull request closed without merging**
