### PR TITLE
Feature - Countdown before game starts

### LINKED ISSUE #7: Add a countdown before game begins
**Describe the solution you'd like**
<liracer> counts down from 3 to 0 before it is possible to type. If you type before that it counts as wrongChars.

Suggested by ~~timblet~~ Goran#0372

### PR DESCRIPTION
**Pull request by lucasvillaverde**
### Description
- Added a simple countdown before the game starts;
- If you type something before countdown ends, it'll be considered a wrong char.

Solves #7

### CODE REVIEW

**Comment by olavfosse** [comment]
Cool. I don't think we should trust the client on this one though.

**Comment by lucasvillaverde** [comment]
> Cool. I don't think we should trust the client on this one though.

Any ideas about it?
I was supposed to implement socket + coutdown calling emit on each count, but don't you think it's overkill? We'll have more traffic and maybe the client won't respect the coutdown timing (1 sec) because of delay.
So I decided to implement one emitting event and let the client handle it then. Since we're computing wrong chars if user types in countdown situation, i think it won't be a problem.

**Comment by olavfosse** [comment]
>Any ideas about it?

The solution I had in mind, was that \<liracer\> would sent a chat message each second of the countdown specifying how many seconds are left til the game starts. Once the game should start, liracer would send a socket.io message announcing the start and beginning to accept 'cursor position' messages.

That way the players can read the quote and "prepare" to type it as the countdown proceeds.

Right now the countdown is not synchronized for everyone in the game either. If a new player joins the game he has to wait three seconds while the others have already begun. Part of the reason for having a countdown system is to give all the players time to get ready. Say a link is posted in a chat room, then the players should have some time to join and get ready before it starts to make it fair for all.
>We'll have more traffic

I am not concerned with traffic until it becomes a problem. I suppose the majority of the traffic comes from `cursor position` messages and sending the frontend build anyhow.

Remember *premature optimization is the root of all evil* :-)

>and maybe the client won't respect the coutdown timing (1 sec) because of delay.

I don't follow here. The point of not trusting the client is that whether or not a client respects the countdown only affects the client itself and not the other players.

**Comment by olavfosse** [comment]
Hello, are you still interested in working on this?

**Comment by lucasvillaverde** [comment]
I made some fixes and moved countdown system to backend. Now, the client will verify the "hasGameBegun" property. I didn't remove "wrong words until countdown ends".
With your explanation, it makes more sense moving these things to socket, thx.

**Pull request closed without merging**
