### PR TITLE
Added fibonacci.cs

### PR DESCRIPTION
**Pull request by Zerplin**
realized I used 2 different types of bracketing earlier

### CODE REVIEW

**Comment by olavfosse** [comment]
Have you run this through snippets.js?

**Comment by Zerplin** [comment]
yes, it returns this

billede

**Comment by Zerplin** [comment]
so should be fine?

**Comment by olavfosse** [comment]
image

**Comment by Zerplin** [comment]
oh, rip ran it properly now. mb

**Pull request closed without merging**
