### PR TITLE
Fix #50

### LINKED ISSUE #50: [LINEFEED] key is not checking properly in Liracer
**Describe the bug**
Enter key (or [LINEFEED] in Ascii) is not recognized correctly in the game. In some snippet, \n is expected to have the Ascii code of 13 which is [CARRIAGE RETURN], however, the Enter Key has the Ascii code of 10 which is [LINEFEED]. Resulting the Liracer always determines that player hit the incorrect key.

**Expected behavior**
It should recognize [LINEFEED] key as the [CARRIAGE RETURN] and vice versa.

**Screenshots**
This is where the snippet code has a breakline character.

image

I put the console.log() in the code for better visualization.

image

**Operating Systems**
Windows 10

**Web Browsers**
Firefox, Microsoft Edge

### PR DESCRIPTION
**Pull request by hungthezorba**

### CODE REVIEW

**Comment by hungthezorba** [comment]
@olav35  I tweaked the code a little bit here base on your pull request. You can test on macOS, on Windows it works as expected.

**Comment by olavfosse** [comment]
Assuming this change fixed your problem, it is not a refactor.

To me the two ternary conditions seem completely equivalent. Comparing a char to carriage return should be equivalent to comparing the charCode of a char to 13. `|| c.charCodeAt(0) === 10` should also not be necessary as if the charcode is 10, returning c should return a newline too.

Can you share the output of running the commands below?
Skjermbilde 2020-10-23 kl  09 53 31

**Comment by hungthezorba** [comment]
image
Here is mine console.
I think if you try comparing each char to check if it equal '\r\n', it will never return true. Because when splitting, '\r' and '\n' is not going together but separated like this.
image

In addition, the '\r' standalone also has the ascii of 13 as well.

**Comment by olavfosse** [comment]
Ah right, my bad. I thought '\r\n' was carriage return not '\r'

**Comment by olavfosse** [comment]
I think I got it. It still works with the latest commit right?

**Comment by hungthezorba** [comment]
> I think I got it. It still works with the latest commit right?

Yeah it works, cleaner than mine. You can merge the pull request now.

**Comment by olavfosse** [comment]
Great merging.

**Pull request merged**
