### PR TITLE
Add cursor visualisation for CodeField focus/blur

### LINKED ISSUE #3: Curser visualisation of whether or not CodeField is selected
**Is your feature request related to a problem? Please describe.**
The problem this is meant to fix is confusion over which box is selected. Since I  use `outline: none` there is no visual way of telling if CodeField is selected as of now.

**Describe the solution you'd like**
Have the cursor be a outline when CodeField is not selected and filled when it is. Other visualisations could work as well.

### PR DESCRIPTION
**Pull request by cobwebsonsale**
Fixes olav35/liracer#3

### CODE REVIEW

**Comment by cobwebsonsale** [comment]
Rebased upstream master to resolve conflicts in .gitignore

**Comment by cobwebsonsale** [comment]
Hey @olav35, does this PR require any changes?

**Comment by olavfosse** [comment]
Apologize for the slow response. I'm reviewing it now.

**Comment by olavfosse** [comment]
I wasn't quite happy with how it looked initially so I changed the visualization. Now it shows a "underline"  in place of the cursor/wrongchar visualization on blur.

**Comment by cobwebsonsale** [comment]
Hey, no worries! And thanks for the edit/merge.

**Comment by olavfosse** [comment]
Cool. I'm always a bit worried about offending someone when rejecting/changing their contributions :p

**Comment by cobwebsonsale** [comment]
xD It's all good. You have some idea in mind with which you've created this repo. I can't get offended at my changes needing modifications to fit that vision.

**Pull request merged**
